:toc:

[id='data-generator-api']
= Data generator API

= Description
This library provides two methods of data generation:
+
Polling:: generated data are returned to user by calling the `requestData(params)` method on Device.
This allows the user to get data on demand with custom parameters.
The number and types of parameters for this method depends mostly on the DataFeed implementation provided for the Device.

Wrapping `Device` with `TimeSimulation`::
//user adds new possibilities for data generation.
In this case the `requestData()` method is called periodically by `TimeSimulation` and it can be used as standalone device.

For data manipulation, the user is advised to perform the following additional steps:

. Configure a `NetworkAdapter` to enable data handling. (This is done the same way as in real-life applications.)
This way data can be sent to valid endpoint using the REST protocol.

. For testing purposes it is recommended to create and `Observer`.
Using the `Observer` pattern, the user is able to catch important information from the data creation process without using debugging tools or viewing log messages.
For infomration on deploying

There are 2 main types of `Device`.
Sensor:: A simple device that contains and performs operations on a single `DataFeed`.
Composition:: Solves a problem, that not all devices are sources of just one type of data. For example commonly known DHT11 temperature-humidity sensor is working with two values simultaneously. This requires possibility to define multiple DataFeeds for one device

The library provides few preconfigured devices that are ready for use. Idea behind them is to simplify creation process for user in case he want to create commonly known devices, but to offer him freedom in configuring his own.
Default
Hygrometer
Thermometer
DefaultComposition
DHT11

The packages currently offered are the following:

DataFeed - tool to provide data streams to different components (e.g. time simulation, simulated devices). This interface is ready for further user customization, as it is not possible to define all situations that could be needed in the future. So far library provides examples, that can be divided into three parts:
SSJ (Stochastic Simulation in Java) - Java library providing tool for stochastic data simulation developed at Université de Montréal (https://www.iro.umontreal.ca/~lecuyer/ssj-gh-pages/html/index.html)
Expression approach, where user defines expression (function) which solutions represents expected data stream
“Logic” driven approach. User is fully capable to customize data generating class as long as it implements DataFeed interface

Device - (Sensor, Composition) back and bone of library, brings parts of the library together. Gives meaning for generated data which are acquired from individual data feeds. Holds information like UUID, label and description.

TimeSimulation - provides possibility to simulate Device in time. Time intervals are determined with data feed like with device. Classes creates environment for device where asynchronous tasks polls data from it. This is way how to simulate real, standalone devices (it is needed to configure NetworkAdapter for time simulated device, for it to be able to snet data with specific protocol to right destination)

DataObservable - simple Observer Pattern, designed for observing Device whenever it produces new data. This is important mostly because time simulation polls data automatically, therefore users ability to retrieve generated value from device is denied. Observer fill this gap by providing tool for catching and reacting for data creation event.
 Usage:
User needs to create new class that implements Observer (https://docs.oracle.com/javase/8/docs/api/java/util/Observer.html).
Device holds list of Observables that will be notified as soon as new data are generated. This list is updated by registering device to DataObservable class
As documented in Observer Pattern, for receiving notifications register our new Observer class to DataObservable by addObserver(observer)

DataWrapper - provides tools that allows to wrap data to common structures like JSON, XML e.t.c.

NetworkAdapter - provides classes when used with device allows user to send data to destination. All he need is to select desired protocol, REST, MQTT or design his own by implementing NetworkAdapter interface and generated data will be delivered to right receiver.

Simple example - device with data on pooling:

Base for our device is properly configured data feed. For this example
`DataFeed dataFeed = new NormalDistributionDataFeed(18, 3);
Create Device with DataFeed. In this case simple Sensor will be enough.
`Sensor device = new Thermometer("ThermometerExample", dataFeed);`
Get generated data
		`device.requestData()`

Simple example - device with data on pooling:

First example is nice, but it returns “random” value from definition scope of normal distribution.
As in first example we need data feed and device
`DataFeed dataFeed = new NormalDistributionDataFeed(18, 3);`
`Sensor device = new Thermometer("ThermometerExample", dataFeed);`



Time Simulation example:

Now, we know how to set up simple device.
Define device as we did in previous examples
In order to simulate device in time - to be able to send data periodically in set intervals, we need to wrap it with running environment called TimeSimulation
Like device, time simulation also needs some data feed to be able determinate mentioned time intervals
`DataFeed timeFeed = new LinearDataFeed(2000);`
We create instance of time simulation
`TimeSimulation sim = new TimeSimulationImpl(timeFeed, device);`
At this point, device needs to configure
Finally, we start simulation
`sim.simulate();`
